spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: 7472
    driver-class-name: com.mysql.cj.jdbc.Driver
    server:
      port: 5050
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true